// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lingfohn/lime/ent/menu"
	"github.com/lingfohn/lime/ent/permission"
	"github.com/lingfohn/lime/ent/role"
	"github.com/lingfohn/lime/ent/schema"
	"github.com/lingfohn/lime/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescWeight is the schema descriptor for weight field.
	menuDescWeight := menuFields[5].Descriptor()
	// menu.DefaultWeight holds the default value on creation for the weight field.
	menu.DefaultWeight = menuDescWeight.Default.(int)
	// menuDescCreatedAt is the schema descriptor for createdAt field.
	menuDescCreatedAt := menuFields[12].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the createdAt field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updatedAt field.
	menuDescUpdatedAt := menuFields[13].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescStatus is the schema descriptor for status field.
	permissionDescStatus := permissionFields[5].Descriptor()
	// permission.DefaultStatus holds the default value on creation for the status field.
	permission.DefaultStatus = permissionDescStatus.Default.(int)
	// permissionDescCreatedAt is the schema descriptor for createdAt field.
	permissionDescCreatedAt := permissionFields[6].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the createdAt field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updatedAt field.
	permissionDescUpdatedAt := permissionFields[7].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleFields[2].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(int)
	// roleDescCreatedAt is the schema descriptor for createdAt field.
	roleDescCreatedAt := roleFields[3].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the createdAt field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updatedAt field.
	roleDescUpdatedAt := roleFields[4].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescInitial is the schema descriptor for initial field.
	userDescInitial := userFields[2].Descriptor()
	// user.DefaultInitial holds the default value on creation for the initial field.
	user.DefaultInitial = userDescInitial.Default.(bool)
	// userDescSuper is the schema descriptor for super field.
	userDescSuper := userFields[8].Descriptor()
	// user.DefaultSuper holds the default value on creation for the super field.
	user.DefaultSuper = userDescSuper.Default.(bool)
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[11].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[12].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
