// Code generated by entc, DO NOT EDIT.

package user

import (
	"time"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"        // FieldUsername holds the string denoting the username vertex property in the database.
	FieldUsername  = "username"  // FieldPassword holds the string denoting the password vertex property in the database.
	FieldPassword  = "password"  // FieldInitial holds the string denoting the initial vertex property in the database.
	FieldInitial   = "initial"   // FieldOauser holds the string denoting the oauser vertex property in the database.
	FieldOauser    = "oauser"    // FieldName holds the string denoting the name vertex property in the database.
	FieldName      = "name"      // FieldTelephone holds the string denoting the telephone vertex property in the database.
	FieldTelephone = "telephone" // FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail     = "email"     // FieldAvatar holds the string denoting the avatar vertex property in the database.
	FieldAvatar    = "avatar"    // FieldSuper holds the string denoting the super vertex property in the database.
	FieldSuper     = "super"     // FieldStatus holds the string denoting the status vertex property in the database.
	FieldStatus    = "status"    // FieldLastLogin holds the string denoting the lastlogin vertex property in the database.
	FieldLastLogin = "lastLogin" // FieldCreatedAt holds the string denoting the createdat vertex property in the database.
	FieldCreatedAt = "createdAt" // FieldUpdatedAt holds the string denoting the updatedat vertex property in the database.
	FieldUpdatedAt = "updatedAt"

	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPassword,
	FieldInitial,
	FieldOauser,
	FieldName,
	FieldTelephone,
	FieldEmail,
	FieldAvatar,
	FieldSuper,
	FieldStatus,
	FieldLastLogin,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// DefaultInitial holds the default value on creation for the initial field.
	DefaultInitial bool
	// DefaultSuper holds the default value on creation for the super field.
	DefaultSuper bool
	// DefaultCreatedAt holds the default value on creation for the createdAt field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	UpdateDefaultUpdatedAt func() time.Time
)
